'use client';
import Link from 'next/link';
import {useState} from 'react';
import {ArrowRight,ArrowUpRight,Copy,Check,House,Share2,Wallet,LifeBuoy,LogOut} from 'lucide-react';
import {createClient} from '@/lib/supabase/client';
import type {EnrollmentState} from '@/lib/partner-enrollment/policy';
import type {PartnerSection} from '@/lib/partner/model';
const money=(cents:number)=>new Intl.NumberFormat('fr-FR',{style:'currency',currency:'EUR'}).format(cents/100);
const nav=[['accueil','Accueil','/partner',House],['partager','Partager','/partner/partager',Share2],['gains','Mes gains','/partner/gains',Wallet],['aide','Aide','/partner/aide',LifeBuoy]] as const;
export function EnrollmentPortal({state,section}:{state:EnrollmentState;section:PartnerSection}){
  const [copied,setCopied]=useState(false),[copyError,setCopyError]=useState(false);
  const e=state.enrollment!;const message=`Découvre FOREAS, l’application pour les chauffeurs VTC. Voici mon lien personnel : ${state.link||''}\n\nJe participe au programme partenaire FOREAS. Cette recommandation peut me donner droit à une commission.`;
  async function copy(value:string){try{await navigator.clipboard.writeText(value);setCopied(true);setCopyError(false);}catch{setCopyError(true);}}
  return <div className="partner-shell partner-portal"><a href="#partner-main" className="partner-skip">Aller au contenu</a><aside className="partner-sidebar"><Link href="https://www.foreas.xyz" className="partner-brand"><img src="/logo-full.svg" width="176" height="36" style={{filter:'brightness(0)'}} alt="FOREAS"/><span>Espace partenaire</span></Link><nav className="partner-nav">{nav.map(([id,label,path,Icon])=><Link key={id} href={path} aria-current={section===id?'page':undefined} className={`partner-nav-link ${section===id?'is-current':''}`}><Icon size={21}/>{label}</Link>)}</nav><div className="partner-sidebar-footer"><p>{e.name}</p><span>{state.email}</span><button className="partner-logout" onClick={async()=>{await createClient().auth.signOut({scope:'local'});window.location.assign('/login?next=%2Fpartner');}}><LogOut size={16}/>Me déconnecter</button></div></aside><main className="partner-main" id="partner-main"><div className="partner-topline"><span>FOREAS · Programme partenaire</span><a href="mailto:contact@foreas.xyz">Besoin d’aide ?</a></div><nav className="enrollment-mobile-nav" aria-label="Espace partenaire">{nav.map(([id,label,path,Icon])=><Link key={id} href={path} aria-current={section===id?'page':undefined}><Icon size={18}/><span>{label}</span></Link>)}</nav><header className="partner-page-header"><p className="partner-kicker">{section==='accueil'?'Ton espace':section==='partager'?'Ton lien personnel':section==='gains'?'Tes commissions':'À tes côtés'}</p><h1>{section==='accueil'?'Bienvenue, '+e.name+'.':section==='partager'?'Partage avec tes mots.':section==='gains'?'Tes gains, étape par étape.':'Une question ? On est là.'}</h1><p>{section==='accueil'?'Ton lien, ton activité et les réponses à tes questions, réunis au même endroit.':section==='partager'?'Une conversation suffit pour faire découvrir FOREAS.':section==='gains'?'Tu retrouves les paiements vérifiés et les commissions associées.':'Retrouve les règles du programme ou écris-nous directement.'}</p></header>
    {!state.ready?<section className="partner-panel"><h2>Ton inscription est enregistrée.</h2><p>Reprends la prochaine étape pour ouvrir ton lien de partage.</p><Link className="enrollment-primary" href="/inscription">Terminer mon inscription<ArrowRight size={18}/></Link></section>:<>
    {(section==='accueil'||section==='partager')&&<section className="partner-panel"><h2>{section==='accueil'?'Ton prochain échange commence ici.':'Ton invitation FOREAS.'}</h2><p>Ton code : <strong>{state.code}</strong></p><label className="enrollment-link-label" htmlFor="referral-link">Ton lien personnel</label><input id="referral-link" className="enrollment-link-input" readOnly value={state.link||''} onFocus={e=>e.target.select()}/><div className="enrollment-share-actions"><button className="enrollment-primary" onClick={()=>void copy(state.link||'')}>{copied?<Check size={17}/>:<Copy size={17}/>} {copied?'Copié':'Copier mon lien'}</button>{section==='accueil'&&<Link className="enrollment-secondary" href="/partner/partager">Préparer mon message<ArrowRight size={17}/></Link>}</div>{copyError&&<p role="alert">La copie automatique est indisponible. Sélectionne ton lien et copie-le.</p>}{section==='partager'&&<><label className="enrollment-link-label" htmlFor="partner-message">Un message pour commencer</label><textarea id="partner-message" className="enrollment-message" defaultValue={message} rows={6}/><p className="partner-caption">Adapte-le à la personne à qui tu écris. Indique toujours que ta recommandation est rémunérée.</p></>}</section>}
    {(section==='accueil'||section==='gains')&&<section className="partner-panel enrollment-panel-spacing"><h2>{section==='accueil'?'Tes premières commissions.':'Un paiement, une trace.'}</h2><p>10 € par mois payé admissible. Le premier mois reste conditionnel jusqu’au paiement confirmé du deuxième mois.</p><div className="enrollment-finance"><div><span>En attente du deuxième mois</span><strong>{money(state.finance?.conditional||0)}</strong></div><div><span>Admissible au versement</span><strong>{money(state.finance?.eligible||0)}</strong></div><div><span>Chauffeurs attribués</span><strong>{state.finance?.referrals||0}</strong></div></div><p className="partner-caption">Une somme admissible n’est pas un virement effectué. Aucun transfert bancaire n’a été déclenché par ton inscription.</p>{section==='gains'&&<div className="enrollment-ledger">{state.finance?.items.length?<><h3>Les dernières commissions</h3><ul>{state.finance.items.map(item=><li key={item.id}><div><strong>{item.kind==='annual'?'Abonnement annuel':'Mois d’abonnement'}</strong><span>{new Date(item.created_at).toLocaleDateString('fr-FR')}</span></div><div><strong>{money(item.amount_cents)}</strong><span>{item.state==='eligible'?'Admissible':item.state==='blocked'?'À vérifier':'Conditionnelle'}</span></div></li>)}</ul></>:<p>Aucune commission pour le moment. Elle apparaîtra ici après un paiement admissible d’un chauffeur attribué à ton lien.</p>}</div>}<Link href="/inscription/conditions" className="partner-text-link">Lire les règles de rémunération<ArrowUpRight size={17}/></Link></section>}
    {section==='aide'&&<div className="partner-home-grid"><section className="partner-panel"><h2>Parlons de ta situation.</h2><p>Inscription, lien, compte Stripe ou commission : écris-nous et précise l’étape qui te bloque.</p><a className="enrollment-primary" href="mailto:contact@foreas.xyz?subject=Mon%20espace%20partenaire%20FOREAS">Contacter FOREAS<ArrowUpRight size={17}/></a><p className="partner-caption">contact@foreas.xyz</p></section><section className="partner-panel"><h2>Ton accord, à portée de main.</h2><p>Conditions acceptées le {e.accepted_at?new Date(e.accepted_at).toLocaleDateString('fr-FR'):'—'}.</p><Link href="/inscription/conditions" className="enrollment-secondary">Relire les conditions<ArrowRight size={17}/></Link><p className="partner-caption">Tu peux arrêter ta participation à tout moment en nous écrivant. Ton accès chauffeur reste indépendant.</p></section></div>}
    </>}
    <footer className="enrollment-footer"><span>© 2026 FOREAS. Tous droits réservés.</span><a href="mailto:contact@foreas.xyz">Contact</a></footer>
  </main></div>;
}
