export const KIT_VERSION='2026-09-12.2';
export const NEW_PARTNER_TERMS_VERSION='2026-09-24.1';
export type KitCommissionPolicy='legacy'|'second_paid_month';
export const audiences = [
  {id:'centre',label:'Centre de formation',moment:'En fin de formation',action:'Présente une fonction concrète, puis laisse les élèves choisir.',intro:'Vous terminez votre formation VTC ? Prenez un moment pour découvrir FOREAS Driver et vérifier si l’outil vous convient.'},
  {id:'loueur',label:'Loueur',moment:'À la remise des clés',action:'Ajoute une fiche au dossier du véhicule. Oriente les questions sur l’app vers FOREAS.',intro:'Avec votre véhicule, voici un outil à découvrir pour votre activité VTC : FOREAS Driver.'},
  {id:'flotte',label:'Flotte ou réseau',moment:'À l’arrivée d’un chauffeur',action:'Explique qui recommande l’app, qui la paie et où demander de l’aide.',intro:'Notre réseau vous propose de découvrir FOREAS Driver. Vous gardez le choix de l’utiliser selon ses conditions.'},
  {id:'createur',label:'Créateur ou communauté',moment:'Quand le sujet aide ton audience',action:'Montre un usage réel, annonce la collaboration et réponds sans promettre de gains.',intro:'Collaboration commerciale avec FOREAS Driver. Voici un outil à examiner pour votre activité VTC.'},
  {id:'chauffeur',label:'Chauffeur parrain',moment:'Après un usage utile, à l’arrêt',action:'Parle à un collègue intéressé. Raconte seulement ce que tu as vraiment vécu.',intro:'Je vous partage FOREAS Driver pour que vous puissiez le découvrir et le juger sur votre propre activité.'},
] as const;
export type AudienceId=typeof audiences[number]['id'];
export function getAudience(id:string){return audiences.find(a=>a.id===id) ?? null;}
export const kitAssets=[
  {asset:'guide.html',title:'Ton guide partenaire',description:'Le bon moment, les étapes et les réponses à donner.',format:'HTML imprimable',personalized:false},
  {asset:'fiche-chauffeur.html',title:'La fiche à remettre au chauffeur',description:'Une découverte simple, avec ton lien quand il est validé.',format:'HTML imprimable',personalized:true},
  {asset:'messages.txt',title:'Trois messages prêts à adapter',description:'Présentation, réponse à une question et dernier suivi utile.',format:'Texte',personalized:true},
] as const;
export function kitId(audience:string,asset:string){return `foreas-driver-${audience}-${asset.replace(/\./g,'-')}`;}
export function personalMessage(audience:AudienceId,url:string){
  const a=getAudience(audience)!;
  return `${a.intro}\n\nFOREAS aide à lire les propositions reconnues. Vérifiez les appareils compatibles, les fonctions et le prix actuel avant de commencer. Le chauffeur garde sa décision.\n\nNotre lien partenaire vous offre 10 % sur votre abonnement mensuel ou annuel, puis à chaque renouvellement. Le prix remisé est confirmé avant le paiement.\n\nLien de recommandation rémunéré : FOREAS peut nous verser une commission si votre abonnement est payé et admissible.\n${url}`;
}
export function messagePack(audience:AudienceId,url:string){return `FOREAS DRIVER — ${getAudience(audience)!.label}\nVersion ${KIT_VERSION}\n\n1. PRÉSENTATION\n${personalMessage(audience,url)}\n\n2. RÉPONSE À UNE QUESTION\nLa démonstration et les conditions actuelles vous permettent de vérifier si FOREAS convient à votre activité. Il n’y a pas de revenu garanti. Notre lien peut nous rémunérer si votre abonnement est admissible : ${url}\n\n3. SUIVI UTILE\nSi vous souhaitez encore examiner FOREAS Driver, voici le lien et les conditions : ${url}\nCe lien peut nous rémunérer. Si cela ne vous intéresse pas, nous n’insisterons pas.\n\nAVANT D’ENVOYER\nAdaptez votre introduction à la relation réelle. Ne prétendez pas avoir utilisé l’app si ce n’est pas vrai. N’envoyez pas les trois messages automatiquement. Respectez un refus. Ne promettez aucune remise qui ne figure pas dans l’offre affichée.\n`;}
export function kitDocument(audience:AudienceId,asset:string,url:string|null,preview:boolean,policy:KitCommissionPolicy='legacy',brand:{css:string;logo:string}={css:'',logo:'<strong>FOREAS / DRIVER</strong>'}){
  const a=getAudience(audience)!;
  const escape=(v:string)=>v.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
  const title=asset==='fiche-chauffeur.html'?'Découvrez FOREAS Driver':`Ton guide · ${a.label}`;
  const paragraphs=asset==='fiche-chauffeur.html' ? [
    ['Une aide pour lire vos propositions','FOREAS Driver aide le chauffeur à lire les propositions reconnues. Vous gardez votre décision. Vérifiez les appareils compatibles et les fonctions actuellement disponibles avant de commencer.'],
    ['Votre avantage avec ce lien','10 % sur votre abonnement mensuel ou annuel, puis à chaque renouvellement de cet abonnement. Le prix remisé est confirmé avant le paiement.'],
    ['Prenez le temps de vérifier','Consultez la démonstration, le prix, les conditions d’essai et la manière d’annuler. Aucun revenu ou résultat n’est garanti.'],
    ['Une recommandation transparente','La personne ou l’organisation qui vous remet ce document peut recevoir une commission de FOREAS lorsque votre abonnement est payé et admissible. Cette commission n’est pas une remise sur votre prix.'],
  ] : [
    [a.moment,a.action],
    ['1. Montrez quelque chose de vrai','Choisissez une fonction actuellement disponible. Si vous utilisez un scénario construit, dites « démonstration ». Ne présentez jamais un montant d’exemple comme un revenu réellement obtenu.'],
    ['2. Laissez choisir','Présentez l’app sans urgence artificielle. Donnez les conditions actuelles. Ne promettez pas une remise qui n’apparaît pas dans l’offre du chauffeur.'],
    ['3. Utilisez votre lien','Partagez uniquement le lien personnel affiché comme disponible dans votre espace. N’utilisez pas un code générique. Ne modifiez pas le code d’un autre partenaire.'],
    ['L’avantage chauffeur','Votre lien partenaire donne 10 % sur le mensuel ou l’annuel, puis à chaque renouvellement de cet abonnement. Votre commission est distincte de cette remise.'],
    ['Votre commission',policy==='second_paid_month'?'10 € par mensualité réellement payée et admissible. 50 € une seule fois au premier annuel payé et admissible. Pour le mensuel, aucun versement avant le deuxième mois payé du même abonnement. Si les deux mensualités sont admissibles, elles représentent 20 € de droits, traités ensuite selon les conditions du programme. Vos droits antérieurs conservent leur règle. Seul l’apporteur direct est rémunéré.':'5 € par mensualité réellement payée et admissible. 50 € une seule fois au premier annuel payé et admissible. Seul l’apporteur direct est rémunéré. Les droits mensuels sont versés le mois suivant selon les conditions du programme.'],
    ['Lire les bons états','Une inscription n’est pas un paiement. Une commission à vérifier, admissible ou en préparation n’est pas encore payée. Les remboursements et litiges peuvent modifier les droits selon les conditions.'],
    ['Répondre sans improviser','La rubrique Aide rassemble les réponses et le document de conditions lorsqu’il est publié. Si une réponse manque, demandez à votre interlocuteur FOREAS avant de la promettre.'],
    ['Adapter à votre métier',audience==='flotte'?'L’achat d’accès par une flotte est une offre différente. Expliquez qui paie, ce que chacun peut voir et ce qui arrive quand un chauffeur quitte la flotte. N’annoncez pas de prix collectif non décidé.':audience==='centre'?'Prévoyez cinq minutes et une seule fonction. Faites expliquer par un élève ce que l’app apporte et ce qu’elle ne garantit pas. Cette démonstration ne constitue pas une certification.':audience==='loueur'?'Remettez la fiche avec les clés. Ne demandez pas au comptoir de résoudre un problème technique de l’app. Gardez une voie claire vers l’aide FOREAS.':audience==='createur'?'Gardez une mention commerciale visible. Les éventuels honoraires de création se discutent séparément de la commission. Ne republiez pas un témoignage ou une image sans droits.':'Partagez à l’arrêt, avec une personne intéressée. Un retour personnel doit correspondre à votre expérience réelle. Un refus met fin aux relances.'],
  ];
  return `<!doctype html><html lang="fr"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${escape(title)} · FOREAS</title><style>${brand.css}body{font-family:Inter,Arial,sans-serif;line-height:1.65;max-width:760px;margin:48px auto;padding:0 24px;color:#111528}header{border-bottom:1px solid #111528;padding-bottom:24px}h1,h2{font-family:Genos,Inter,Arial,sans-serif;line-height:1.15}h1{font-size:36px}h2{font-size:23px;margin-top:28px}a{color:#6C3CE0;overflow-wrap:anywhere}footer{margin-top:36px;border-top:1px solid #111528;padding-top:16px;font-size:13px}.note{font-weight:600}@media print{body{margin:0;max-width:none}section{break-inside:avoid}}</style></head><body><header>${brand.logo}<h1>${escape(title)}</h1><p>${escape(a.label)} · Version ${KIT_VERSION}${policy==='second_paid_month'?` · Conditions ${NEW_PARTNER_TERMS_VERSION}`:''}</p>${preview?'<p class="note">Aperçu local du support. Aucun compte, gain ou lien personnel réel n’est utilisé.</p>':''}</header>${paragraphs.map(([h,t])=>`<section><h2>${escape(h)}</h2><p>${escape(t)}</p></section>`).join('')}<section><h2>Pour continuer</h2>${url?`<p><a href="${escape(url)}">Ouvrir votre invitation FOREAS Driver</a><br>${escape(url)}</p>`:'<p>Le lien personnel sera ajouté lorsque l’admission et les conditions seront confirmées. Ce support ne contient pas de code générique.</p>'}</section><footer>Le prix de l’app et la commission sont distincts. Respectez les conditions actuelles du programme. Conservez une copie datée ; remplacez les anciennes versions.</footer></body></html>`;
}
