import Link from 'next/link';
import { GlassCard } from '@/components/foreas/GlassCard';
import { getAdminPartners } from '@/lib/partner/admin-program-server';
import { partnerListQuerySchema,type AdminPartnerListRow } from '@/lib/partner/admin-program';
import { PROMESSE_PARRAINAGE } from '@/lib/parrainagePromesse';
const labels={active:'Actif',pending:'En attente',paused:'En pause'};
const profiles:Record<string,string>={centre:'Centre',auto_ecole:'Auto-école',loueur:'Loueur',flotte:'Flotte',fleet_manager:'Gestionnaire de flotte',createur:'Créateur',influencer:'Créateur',agent_commercial:'Agent commercial',federation:'Fédération'};
export default async function AdminPartnersPage({searchParams}:{searchParams:Promise<Record<string,string|string[]|undefined>>}){
 const raw=await searchParams;
 const parsed=partnerListQuerySchema.safeParse(Object.fromEntries(Object.entries(raw).filter(([key,value])=>value!==undefined&&value!==''&&!(key==='status'&&value==='all'))));
 if(!parsed.success)return <section><h1 className="font-display text-h1">Filtres non reconnus</h1><Link href="/admin/partners" className="font-display inline-flex min-h-12 items-center underline">Ouvrir les dossiers sans filtre</Link></section>;
 const query=parsed.data;let partners:AdminPartnerListRow[]|null=null;
 try{partners=await getAdminPartners();}catch{/* An unavailable collection is never an empty result. */}
 const term=(query.q??'').trim().toLocaleLowerCase('fr');
 const filtered=partners?.filter(p=>(!query.status||p.status===query.status)&&(!term||[p.company_name,p.contact_email,p.referral_code??''].some(value=>value.toLocaleLowerCase('fr').includes(term))));
 const page=Number(query.page??1),pageSize=25,rows=filtered?.slice((page-1)*pageSize,page*pageSize);
 function pageUrl(n:number){const q=new URLSearchParams();if(query.status)q.set('status',query.status);if(query.q)q.set('q',query.q);q.set('page',String(n));return `/admin/partners?${q}`;}
 return <div className="space-y-xl text-text-secondary">
  <header className="space-y-md"><h1 className="font-display text-display-l text-text-primary">Partenaires</h1><p>{PROMESSE_PARRAINAGE}</p><p>Consultez un dossier pour lire ses droits confirmés. Les anciens compteurs financiers ne sont pas utilisés ici.</p><div className="flex flex-wrap gap-lg"><Link href="/admin/partner-pending" className="font-display inline-flex min-h-12 items-center underline">Examiner les candidatures</Link><Link href="/admin/payouts" className="font-display inline-flex min-h-12 items-center underline">Lire les commissions</Link></div></header>
  <form method="get" className="flex flex-wrap items-end gap-md"><div><label htmlFor="partner-search" className="block mb-xs">Société, email ou code enregistré</label><input id="partner-search" name="q" maxLength={200} defaultValue={query.q??''} className="min-h-12 rounded-lg border border-glass-border bg-glass-low px-md"/></div><div><label htmlFor="partner-state" className="block mb-xs">État enregistré</label><select id="partner-state" name="status" defaultValue={query.status??''} className="min-h-12 rounded-lg border border-glass-border bg-glass-low px-md"><option value="">Tous les états</option>{Object.entries(labels).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></div><button className="font-display min-h-12 px-lg rounded-lg border border-glass-border">Rechercher</button></form>
  {partners===null?<GlassCard><div role="alert"><h2 className="font-display text-h2 text-text-primary">Dossiers indisponibles</h2><p>La liste n’a pas pu être vérifiée. Cela ne signifie pas qu’elle est vide.</p><Link href="/admin/partners" className="font-display inline-flex min-h-12 items-center underline">Réessayer la lecture</Link></div></GlassCard>:<GlassCard>
   <p className="mb-md">Recherche et pages limitées aux dossiers reçus du service. Cette réponse ne confirme pas que tous les partenaires ont été renvoyés.</p>
   <p className="mb-md">{filtered!.length} dossier{filtered!.length>1?'s':''} reçu{filtered!.length>1?'s':''} correspondant au filtre.</p>
   {rows!.length===0?<p>{page>1?'Aucun dossier sur cette page. Revenez à la première page pour actualiser la recherche.':'Aucun dossier reçu ne correspond à cette recherche.'}</p>:<div className="overflow-x-auto"><table className="w-full text-left"><caption className="sr-only">Dossiers partenaires reçus, sans total financier</caption><thead><tr>{['Société','Profil enregistré','État enregistré','Code enregistré','Dossier'].map(label=><th key={label} scope="col" className="p-md border-b border-glass-border">{label}</th>)}</tr></thead><tbody>{rows!.map(p=><tr key={p.id}><td className="p-md border-b border-glass-border"><p className="text-text-primary">{p.company_name}</p><p>{p.contact_email}</p></td><td className="p-md border-b border-glass-border">{p.company_type?(profiles[p.company_type]??p.company_type):'Non renseigné'}</td><td className="p-md border-b border-glass-border">{labels[p.status]}</td><td className="p-md border-b border-glass-border break-all">{p.referral_code??'Non renseigné'}</td><td className="p-md border-b border-glass-border"><Link href={`/admin/partners/${p.id}`} className="font-display inline-flex min-h-12 items-center underline">Ouvrir {p.company_name}</Link></td></tr>)}</tbody></table></div>}
   <nav aria-label="Pages des dossiers reçus" className="mt-md flex gap-lg">{page>1&&<Link href={pageUrl(1)} className="font-display inline-flex min-h-12 items-center underline">Première page</Link>}{page>1&&rows!.length>0&&<Link href={pageUrl(page-1)} className="font-display inline-flex min-h-12 items-center underline">Page précédente</Link>}{page*pageSize<filtered!.length&&<Link href={pageUrl(page+1)} className="font-display inline-flex min-h-12 items-center underline">Page suivante</Link>}</nav>
  </GlassCard>}
 </div>;
}
