const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),{createRequire}=require('node:module');
const root=path.resolve(__dirname,'../..'),pkg=createRequire(path.join(root,'package.json'));
const ts=pkg('typescript'),React=pkg('react'),renderer=pkg('react-test-renderer');global.IS_REACT_ACT_ENVIRONMENT=true;
const A='11111111-1111-4111-8111-111111111111',B='22222222-2222-4222-8222-222222222222',at='2026-09-08T21:00:00Z';
const input={discount_percent_for_recruits:10,discount_duration_months:3,landing_message:null,landing_hero_url:null,is_promo_active:true};
const partner={id:A,company_name:'Organisation fictive',contact_email:'test@example.invalid',company_type:'centre',status:'pending',referral_code:null,approved_at:null,...input};
// A valid current read carries its observation date and transfer evidence.
const right={id:B,sponsor_id:A,sponsor_type:'partner',kind:'monthly_paid',status:'eligible',amount_cents:500,currency:'EUR',invoice_paid_at:'2026-08-08T21:00:00Z',eligible_at:'2026-09-01T00:00:00Z',payout_month:'2026-09',paid_at:null,created_at:at,right_status:'eligible',transfer_confirmed:false,reservation_state:null,batch_review_required:false,right_review_required:false};
const ledger={evidence_version:'commission-evidence.v1',observed_at:at,items:[right],pagination:{limit:25,next_cursor:'opaque-test'},coverage:{ledger:'parrainage_droits',legacy_reconciled:false,transfer_basis:'recorded_provider_confirmation',bank_receipt:'not_tracked',transfer_reversals:'not_reconciled'}};
function setup(extra={}){
 let admin=true,origin='https://backend.test.invalid',body={ok:true,partner:{id:A,...input}},http=200;const calls=[],refreshes=[];let refreshCount=0;
 const common={'server-only':{},react:React,'react/jsx-runtime':pkg('react/jsx-runtime'),zod:pkg('zod'),
 '@/lib/queries/admin':{isCurrentUserAdmin:async()=>admin},'@/lib/partner/server':{backendOrigin:()=>origin,partnerSession:async()=> 'synthetic',partnerGet:async(url,schema)=>{calls.push({url,method:'GET'});return {status:'ready',data:schema.parse(ledger),asOf:at}}},
 'next/cache':{revalidatePath:p=>refreshes.push(p)},'next/link':{__esModule:true,default:'a'},'next/navigation':{useRouter:()=>({refresh(){refreshCount++;}}),notFound:()=>{throw Error('NOT_FOUND')}},
 '@/components/foreas/GlassCard':{GlassCard:({children})=>React.createElement('section',null,children)},...extra};
 const loaded=new Map();function load(rel){let file=path.join(root,rel);if(!fs.existsSync(file))file=['.ts','.tsx'].map(ext=>file+ext).find(fs.existsSync);if(!file)throw Error('MISSING_FILE '+rel);if(loaded.has(file))return loaded.get(file);const m={exports:{}};loaded.set(file,m.exports);
 const js=ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.CommonJS,jsx:ts.JsxEmit.ReactJSX,esModuleInterop:true}}).outputText;
 vm.runInNewContext(js,{module:m,exports:m.exports,require:name=>{if(name in common)return common[name];if(name.startsWith('@/'))return load(name.slice(2));if(name.startsWith('.')){const rel=path.relative(root,path.resolve(path.dirname(file),name));return ('@/'+rel) in common?common['@/'+rel]:load(rel);}throw Error('FORBIDDEN_IMPORT '+name)},URL,URLSearchParams,AbortSignal,console,fetch:async(url,opts)=>{calls.push({url,...opts});return{ok:http===200,status:http,json:async()=>body}}},{filename:file});loaded.set(file,m.exports);return m.exports;}
 return {load,calls,refreshes,setAdmin:v=>admin=v,setOrigin:v=>origin=v,setResponse:(v,status=200)=>{body=v;http=status},refreshCount:()=>refreshCount};
}
const text=value=>JSON.stringify(value);
async function render(element){let tree;await renderer.act(async()=>{tree=renderer.create(element)});return tree;}
async function close(tree){await renderer.act(async()=>tree.unmount());}
test('commission libre refusée avant toute modification de remise',async()=>{const h=setup(),a=h.load('app/(admin)/admin/partners/[id]/actions.ts');await assert.rejects(()=>a.updatePartnerDiscount(A,{...input,commission_rate:35}));assert.equal(h.calls.length,0);assert.equal(h.refreshes.length,0)});
test('une remise valide ne passe que par la voie protégée, sans écriture directe',async()=>{const h=setup(),a=h.load('app/(admin)/admin/partners/[id]/actions.ts');await a.updatePartnerDiscount(A,input);assert.equal(h.calls.length,1);assert.equal(h.calls[0].url,`https://backend.test.invalid/api/admin/partners/${A}/discount`);assert.deepEqual(JSON.parse(h.calls[0].body),input);assert.equal(h.calls[0].headers.Authorization,'Bearer synthetic');assert.equal(h.refreshes.length,2)});
test('administrateur non vérifié refusé avant lecture et sauvegarde',async()=>{const h=setup();h.setAdmin(false);const a=h.load('app/(admin)/admin/partners/[id]/actions.ts');await assert.rejects(()=>a.updatePartnerDiscount(A,input));const r=await h.load('lib/partner/admin-program-server.ts').getAdminRights({});assert.equal(r.status,'unavailable');assert.equal(h.calls.length,0)});
test('configuration absente ne reprend aucun domaine de production implicite',async()=>{const h=setup();h.setOrigin(null);await assert.rejects(()=>h.load('app/(admin)/admin/partners/[id]/actions.ts').updatePartnerDiscount(A,input));assert.equal(h.calls.length,0)});
for(const variant of ['wrong_partner','wrong_discount','missing_ok','provider_failure'])test('sauvegarde non confirmée : '+variant,async()=>{const h=setup();h.setResponse(variant==='wrong_partner'?{ok:true,partner:{id:B,...input}}:variant==='wrong_discount'?{ok:true,partner:{id:A,...input,discount_percent_for_recruits:20}}:variant==='missing_ok'?{partner:{id:A,...input}}:{error:'failed'},variant==='provider_failure'?503:200);await assert.rejects(()=>h.load('app/(admin)/admin/partners/[id]/actions.ts').updatePartnerDiscount(A,input));assert.equal(h.refreshes.length,0)});
test('demande ancienne de versement ne contacte aucun service',async()=>{const h=setup();await assert.rejects(()=>h.load('app/(admin)/admin/payouts/actions.ts').runCronNow(),/retirée/);assert.equal(h.calls.length,0);assert.equal(h.load('app/(admin)/admin/payouts/RunCronButton.tsx').RunCronButton(),null)});
test('activation annonce seulement le retour confirmé du service d’admission',async()=>{const h=setup(),a=h.load('app/(admin)/admin/partners/[id]/actions.ts');h.setResponse({ok:true,status:'paused'});await assert.rejects(()=>a.updatePartnerStatus(A,'active'));assert.equal(h.refreshes.length,0);h.setResponse({ok:true,status:'active'});await a.updatePartnerStatus(A,'active');assert.equal(h.calls[1].url,`https://backend.test.invalid/api/admin/partners/${A}/status`)});
test('relevé demande uniquement les droits canoniques avec filtres encodés',async()=>{const h=setup();await h.load('lib/partner/admin-program-server.ts').getAdminRights({sponsor_id:A,sponsor_type:'partner',status:'paid',cursor:'a&b'});const url=h.calls[0].url;assert.match(url,/^\/api\/admin\/partner-finance\/rights\?/);const q=new URL('https://test.invalid'+url).searchParams;assert.equal(q.get('limit'),'25');assert.equal(q.get('cursor'),'a&b');assert.equal(q.get('sponsor_id'),A);assert.equal(q.get('status'),'paid')});
test('filtre de partenaire incomplet ou liste injectée refusé avant lecture',async()=>{const h=setup(),a=h.load('lib/partner/admin-program-server.ts');await assert.rejects(()=>a.getAdminRights({sponsor_id:A}));await assert.rejects(()=>a.getAdminRights({status:['paid','eligible']}));assert.equal(h.calls.length,0)});
test('contrat ancien, négatif ou mal daté refusé au lieu de devenir zéro',()=>{const schema=setup().load('lib/partner/admin-program.ts').adminRightsSchema;assert.equal(schema.safeParse(ledger).success,true);for(const data of [{pending:[],total_eur:0},{...ledger,items:[{...right,amount_cents:-500}]},{...ledger,items:[{...right,created_at:'invalid'}]},{...ledger,coverage:{ledger:'partner_commissions',legacy_reconciled:true}}])assert.equal(schema.safeParse(data).success,false)});
test('page indisponible ne fabrique ni zéro ni bouton de versement',async()=>{const h=setup({'@/lib/partner/admin-program-server':{getAdminRights:async()=>({status:'unavailable',code:'SERVICE_UNAVAILABLE'})}});const page=await h.load('app/(admin)/admin/payouts/page.tsx').default({searchParams:Promise.resolve({})});const tree=await render(page);const out=text(tree.toJSON());assert.match(out,/Relevé indisponible/);assert.doesNotMatch(out,/0,00|à verser ce mois|Run cron|le 5 du mois/);await close(tree)});
test('page suivante conserve le partenaire et état, sans total depuis la page',async()=>{const h=setup();const page=await h.load('app/(admin)/admin/payouts/page.tsx').default({searchParams:Promise.resolve({sponsor_id:A,sponsor_type:'partner',status:'eligible'})});const tree=await render(page);const links=tree.root.findAllByType('a'),next=links.find(x=>x.props.href.includes('cursor='));assert.ok(next);const q=new URL('https://test.invalid'+next.props.href).searchParams;assert.equal(q.get('sponsor_id'),A);assert.equal(q.get('status'),'eligible');const out=text(tree.toJSON());assert.match(out,/5,00/);assert.doesNotMatch(out,/Total à verser|10 €|N1|N2|N3/);await close(tree)});
test('fiche ignore les chiffres historiques de l’ancienne lecture et garde le profil exact',async()=>{const h=setup();h.setResponse({partner:{...partner,total_earned:987654,pending_commission:123456},commissions:[{amount:999}],recruits:[{total_earned:999}]});const page=await h.load('app/(admin)/admin/partners/[id]/page.tsx').default({params:Promise.resolve({id:A})});const tree=await render(page);const out=text(tree.toJSON());assert.match(out,/Organisation fictive/);assert.doesNotMatch(out,/987654|123456|Commission par filleul|25 \/ 35 \/ 50/);await close(tree)});
test('formulaire refuse double appui et ignore un succès après remplacement du dossier',async()=>{let resolve,calls=0;const waiting=new Promise(r=>resolve=r);const h=setup({'./actions':{updatePartnerDiscount:async()=>{calls++;await waiting;}}}),Form=h.load('app/(admin)/admin/partners/[id]/DiscountForm.tsx').DiscountForm;const tree=await render(React.createElement(Form,{partner}));await renderer.act(async()=>{tree.root.findByType('form').props.onSubmit({preventDefault(){}});tree.root.findByType('form').props.onSubmit({preventDefault(){}})});assert.equal(calls,1);await close(tree);await renderer.act(async()=>resolve());assert.equal(h.refreshCount(),0)});
test('préférence non renseignée ne devient pas zéro à la sauvegarde',async()=>{let calls=0;const h=setup({'./actions':{updatePartnerDiscount:async()=>calls++}}),Form=h.load('app/(admin)/admin/partners/[id]/DiscountForm.tsx').DiscountForm;const tree=await render(React.createElement(Form,{partner:{...partner,discount_percent_for_recruits:null}}));await renderer.act(async()=>tree.root.findByType('form').props.onSubmit({preventDefault(){}}));assert.equal(calls,0);assert.match(text(tree.toJSON()),/Vérifiez la remise/);await close(tree)});
test('phrase canonique ne promet aucun jour bancaire fixe',()=>{const p=setup().load('lib/parrainagePromesse.ts');assert.match(p.PROMESSE_PARRAINAGE,/5 €.*mensualité.*50 €.*une seule fois.*premier annuel.*mois suivant/);assert.doesNotMatch(p.PROMESSE_PARRAINAGE,/le 25|le 5 /)});
test('liste réelle ignore un ancien revenu élevé, sans compteurs financiers ni cascade',async()=>{const h=setup();h.setResponse({partners:[{...partner,created_at:at,total_earned:987654321,pending_commission:456789,total_drivers:999999}]});const page=await h.load('app/(admin)/admin/partners/page.tsx').default({searchParams:Promise.resolve({})});const tree=await render(page),out=text(tree.toJSON());assert.match(out,/Organisation fictive/);assert.doesNotMatch(out,/987654321|456789|999999|Total commissions|cascade|N1\/N2/);assert.match(out,/limitées aux dossiers reçus/);await close(tree)});
test('liste indisponible ne se replie pas vers des zéros ou une autre lecture',async()=>{const h=setup();h.setResponse({error:'indisponible'},503);const page=await h.load('app/(admin)/admin/partners/page.tsx').default({searchParams:Promise.resolve({})});const tree=await render(page),out=text(tree.toJSON());assert.equal(h.calls.length,1);assert.match(out,/Dossiers indisponibles/);assert.doesNotMatch(out,/0 dossier|Aucun partenaire enregistré|0,00/);await close(tree)});
test('liste mal formée ne force pas une identité ou un état par défaut',async()=>{const h=setup();h.setResponse({partners:[{...partner,created_at:at,status:'inconnu'}]});const tree=await render(await h.load('app/(admin)/admin/partners/page.tsx').default({searchParams:Promise.resolve({})}));assert.match(text(tree.toJSON()),/Dossiers indisponibles/);assert.doesNotMatch(text(tree.toJSON()),/Organisation fictive/);await close(tree)});
test('pagination locale reste bornée à la réponse et conserve la recherche',async()=>{const h=setup();h.setResponse({partners:Array.from({length:27},(_,i)=>({...partner,id:`11111111-1111-4111-8111-${String(i+1).padStart(12,'0')}`,company_name:`all fictif ${i+1}`,created_at:at,status:'active'}))});const tree=await render(await h.load('app/(admin)/admin/partners/page.tsx').default({searchParams:Promise.resolve({q:'all',status:'active',page:'2'})}));assert.equal(tree.root.findAllByType('tbody')[0].findAllByType('tr').length,2);const first=tree.root.findAllByType('a').find(a=>a.props.href.includes('page=1'));assert.ok(first);assert.equal(new URL('https://test.invalid'+first.props.href).searchParams.get('q'),'all');assert.match(text(tree.toJSON()),/ne confirme pas que tous les partenaires/);assert.equal(h.calls[0].url,'https://backend.test.invalid/api/admin/partners');await close(tree)});
test('liste refuse les paramètres multiples avant la première lecture',async()=>{const h=setup();const tree=await render(await h.load('app/(admin)/admin/partners/page.tsx').default({searchParams:Promise.resolve({status:['active','paused']})}));assert.match(text(tree.toJSON()),/Filtres non reconnus/);assert.equal(h.calls.length,0);await close(tree)});
test('erreur de lecture des candidatures ne retourne jamais un tableau vide',async()=>{let calls=0;const chain={select(){return this},eq(){return this},async order(){calls++;return{data:null,error:{message:'panne fictive'}}}};const h=setup({'@/lib/supabase/server':{createClient:async()=>({from:()=>chain})}});await assert.rejects(()=>h.load('lib/queries/partner-applications.ts').getPendingApplications());assert.equal(calls,1);h.setAdmin(false);await assert.rejects(()=>h.load('lib/queries/partner-applications.ts').getPendingApplications());assert.equal(calls,1)});
test('candidatures : une lecture partielle reste visible sans faux total ni activation automatique',async()=>{const h=setup({'@/lib/queries/partner-applications':{getPendingApplications:async()=>{throw Error('panne fictive')}},'./ApproveActions':{ApproveActions:()=>React.createElement('span',null,'Action existante simulée')},'./ApplicationActions':{ApplicationActions:()=>null}});h.setResponse({partners:[{...partner,created_at:at,total_earned:999999}]});const tree=await render(await h.load('app/(admin)/admin/partner-pending/page.tsx').default());const out=text(tree.toJSON());assert.match(out,/Les candidatures du site sont indisponibles/);assert.match(out,/Organisation fictive/);assert.doesNotMatch(out,/Aucune candidature en attente|génère.*Stripe|999999|Partners MLM/);assert.match(out,/Une invitation ne part que si elle est demandée explicitement/);await close(tree)});
